version: '3.8'

services:
  app:
    build: .
    container_name: ellis-app
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    # command: ["sh", "-c", "comando-para-iniciar-sua-app"]